# Generated by Django 3.0.4 on 2020-04-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payaccount',
            options={'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
    ]
