# Generated by Django 3.0.4 on 2020-04-18 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_categoryads_formatads'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='category_ads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.CategoryAds', verbose_name='Тип рекламы'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='format_ads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.FormatAds', verbose_name='Тип рекламы'),
        ),
    ]
