# Generated by Django 3.0.4 on 2020-04-12 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20200412_2145'),
        ('tasks', '0002_auto_20200412_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='types_ads',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='settings.TypesAds', verbose_name='Тип рекламы'),
        ),
    ]
