# Generated by Django 3.0.4 on 2020-04-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('type_user', models.CharField(choices=[('adventiser', 'Рекламодатель'), ('playground', 'Игровая площадка')], default='adventiser', max_length=100, verbose_name='Тип пользователя')),
                ('telephone', models.BigIntegerField(blank=True, null=True, verbose_name='телефон')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'пользовательские данные',
                'verbose_name_plural': 'пользовательские данные',
            },
        ),
    ]
