# Generated by Django 3.0.4 on 2020-04-11 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_user', models.CharField(choices=[('adventiser', 'Рекламодатель'), ('playgrounds', 'Игровая площадка')], default='adventiser', max_length=100, verbose_name='Тип пользователя')),
                ('telephone', models.BigIntegerField(blank=True, null=True, verbose_name='телефон')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('advertiser_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Advertiser', verbose_name='Рекламодатель')),
                ('playground_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Playgrounds', verbose_name='Игровая площадка')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'пользовательские данные',
                'verbose_name_plural': 'пользовательские данные',
            },
        ),
    ]
